// <auto-generated />
using LOL_int_list_GUI_v2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LOL_int_list_GUI_v2.Migrations
{
    [DbContext(typeof(SummonerContext))]
    [Migration("20200101013720_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LOL_int_list_GUI_v2.Summoner", b =>
                {
                    b.Property<string>("summonerName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("summonerName");

                    b.ToTable("Summoners");
                });
#pragma warning restore 612, 618
        }
    }
}
